### ISSUE TITLE
Debian package out of date and broken

### ISSUE THREAD

**Issue by abb128** [Nihlus/Crystite#6]
I tried to update Crystite server today but encountered this error:
> The installed Resonite version (2024.2.5.848) does not match the version Crystite was compiled with (2024.1.3.1265)

There is no newer package
> crystite is already the newest version (1.0.0+deb11~preview33).

The README recommends using the Debian repository at `https://repo.algiz.nu/crystite`, but it looks like this repo's latest version is preview33 which is behind the latest preview41

If I manually ping the server with this, there appears to be nothing greater than preview33
```
curl -H 'User-Agent: Debian APT-HTTP/1.3' https://repo.algiz.nu/crystite/dists/bullseye/main/binary-amd64/Packages  | grep Version
```

**Comment by uyjulian** [comment]
Use Debian 12 / bookworm. Debian 11 packages aren't being uploaded anymore

**Comment by Nihlus** [comment]
Closing as wontfix; as the previous comment stated, Crystite is only available for Debian 12 as of a number of versions ago.

**Comment by abb128** [comment]
That makes more sense, I suggest updating the README as it still mentions Debian 11

**Comment by Nihlus** [comment]
Good catch - I've fixed that :)
